name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start containers
        run: docker compose up -d --build

      - name: Wait for Postgres and Redis to be ready
        run: |
          echo "Waiting for Postgres..."
          docker compose exec -T postgres sh -c 'until pg_isready -U postgres; do sleep 2; done'
          echo "Waiting for Redis..."
          docker compose exec -T redis sh -c 'until redis-cli ping | grep PONG; do sleep 2; done'

      - name: Install Laravel dependencies and setup
        run: |
          docker compose exec -T backend cp .env.ci .env
          docker compose exec -T backend composer install --no-dev --optimize-autoloader
          docker compose exec -T backend php artisan key:generate
          docker compose exec -T backend php artisan config:cache

      - name: Run Laravel migrations
        run: docker compose exec -T backend php artisan migrate --force

      - name: Check Laravel commands
        run: |
          docker compose exec -T backend php artisan --version
          docker compose exec -T backend php artisan list | grep test || true

      - name: Run backend tests (Laravel)
        run: |
          echo "Running PHPUnit tests..."
          docker compose exec -T backend ./vendor/bin/phpunit || \
          docker compose exec -T backend vendor/bin/phpunit || \
          echo "No tests found or PHPUnit not installed"

      - name: Run frontend tests (Vue)
        run: docker compose exec -T frontend npm run test

      - name: Run frontend build (Vue)
        run: docker compose exec -T frontend npm run build

      - name: Tear down containers
        if: always()
        run: docker compose down -v
